import { Template } from './types';

export const templates: Template[] = [
  {
    id: 'tpl-fin-annual-2024',
    name: 'Annual Financial Report',
    description: 'Comprehensive annual report with financial highlights, KPIs, and year-over-year analysis.',
    category: 'financial',
    slideCount: 24,
    lastUpdated: '2024-12-15',
    version: '2.1',
    fields: [
      {
        id: 'fiscal_year',
        label: 'Fiscal Year',
        type: 'select',
        required: true,
        options: ['2024', '2025', '2026'],
      },
      {
        id: 'revenue',
        label: 'Total Revenue (EUR M)',
        type: 'number',
        placeholder: '25000',
        required: true,
        hint: 'Enter value in millions',
      },
      {
        id: 'net_income',
        label: 'Net Income (EUR M)',
        type: 'number',
        placeholder: '2500',
        required: true,
      },
      {
        id: 'ebitda',
        label: 'EBITDA (EUR M)',
        type: 'number',
        placeholder: '4200',
        required: true,
      },
      {
        id: 'executive_summary',
        label: 'Executive Summary',
        type: 'textarea',
        placeholder: 'Overview of annual performance and key achievements...',
        required: true,
      },
      {
        id: 'key_achievements',
        label: 'Key Achievements',
        type: 'textarea',
        placeholder: 'List major milestones (one per line)',
        required: true,
      },
      {
        id: 'outlook',
        label: 'Future Outlook',
        type: 'textarea',
        placeholder: 'Strategic direction and expectations...',
        required: false,
      },
    ],
  },
  {
    id: 'tpl-esg-2024',
    name: 'ESG Sustainability Report',
    description: 'Environmental, Social, and Governance metrics with sustainability initiatives.',
    category: 'esg',
    slideCount: 32,
    lastUpdated: '2024-11-20',
    version: '1.4',
    fields: [
      {
        id: 'reporting_period',
        label: 'Reporting Period',
        type: 'text',
        placeholder: 'Jan 2024 - Dec 2024',
        required: true,
      },
      {
        id: 'carbon_emissions',
        label: 'Carbon Emissions (t CO2e)',
        type: 'number',
        placeholder: '15000000',
        required: true,
      },
      {
        id: 'emission_reduction',
        label: 'YoY Emission Reduction (%)',
        type: 'number',
        placeholder: '8.5',
        required: true,
      },
      {
        id: 'renewable_share',
        label: 'Renewable Energy Share (%)',
        type: 'number',
        placeholder: '25',
        required: true,
      },
      {
        id: 'environmental_initiatives',
        label: 'Environmental Initiatives',
        type: 'textarea',
        placeholder: 'Key environmental programs and outcomes...',
        required: true,
      },
      {
        id: 'social_programs',
        label: 'Social Programs',
        type: 'textarea',
        placeholder: 'Community and employee initiatives...',
        required: true,
      },
      {
        id: 'governance',
        label: 'Governance Highlights',
        type: 'textarea',
        placeholder: 'Board diversity, compliance measures...',
        required: true,
      },
    ],
  },
  {
    id: 'tpl-ir-deck',
    name: 'Investor Relations Deck',
    description: 'Investor presentation with company overview and investment highlights.',
    category: 'investor',
    slideCount: 18,
    lastUpdated: '2024-12-01',
    version: '3.0',
    fields: [
      {
        id: 'presentation_date',
        label: 'Presentation Date',
        type: 'date',
        required: true,
      },
      {
        id: 'company_overview',
        label: 'Company Overview',
        type: 'textarea',
        placeholder: 'Market position and competitive advantages...',
        required: true,
      },
      {
        id: 'market_cap',
        label: 'Market Cap (EUR B)',
        type: 'number',
        placeholder: '8.5',
        required: true,
      },
      {
        id: 'share_price',
        label: 'Share Price (EUR)',
        type: 'number',
        placeholder: '2850',
        required: true,
      },
      {
        id: 'dividend_yield',
        label: 'Dividend Yield (%)',
        type: 'number',
        placeholder: '4.2',
        required: false,
      },
      {
        id: 'investment_highlights',
        label: 'Investment Highlights',
        type: 'textarea',
        placeholder: 'Key reasons to invest...',
        required: true,
      },
    ],
  },
  {
    id: 'tpl-quarterly',
    name: 'Quarterly Results',
    description: 'Quarterly earnings with segment performance and guidance.',
    category: 'quarterly',
    slideCount: 16,
    lastUpdated: '2025-01-10',
    version: '2.3',
    fields: [
      {
        id: 'quarter',
        label: 'Quarter',
        type: 'select',
        required: true,
        options: ['Q1', 'Q2', 'Q3', 'Q4'],
      },
      {
        id: 'year',
        label: 'Year',
        type: 'select',
        required: true,
        options: ['2024', '2025', '2026'],
      },
      {
        id: 'revenue',
        label: 'Revenue (EUR M)',
        type: 'number',
        placeholder: '6200',
        required: true,
      },
      {
        id: 'yoy_growth',
        label: 'YoY Growth (%)',
        type: 'number',
        placeholder: '12.5',
        required: true,
      },
      {
        id: 'segment_breakdown',
        label: 'Segment Performance',
        type: 'textarea',
        placeholder: 'Performance by business segment...',
        required: true,
      },
      {
        id: 'guidance',
        label: 'Forward Guidance',
        type: 'textarea',
        placeholder: 'Outlook for upcoming quarters...',
        required: false,
      },
    ],
  },
  {
    id: 'tpl-strategy-2030',
    name: 'Strategic Plan 2030',
    description: 'Long-term strategic planning with vision and transformation roadmap.',
    category: 'strategy',
    slideCount: 28,
    lastUpdated: '2024-10-05',
    version: '1.2',
    fields: [
      {
        id: 'horizon',
        label: 'Strategy Horizon',
        type: 'text',
        placeholder: '2025-2030',
        required: true,
      },
      {
        id: 'vision',
        label: 'Vision Statement',
        type: 'textarea',
        placeholder: 'Company vision for the period...',
        required: true,
      },
      {
        id: 'pillars',
        label: 'Strategic Pillars',
        type: 'textarea',
        placeholder: 'Key strategic pillars (one per line)',
        required: true,
      },
      {
        id: 'financial_targets',
        label: 'Financial Targets',
        type: 'textarea',
        placeholder: 'Key financial milestones...',
        required: true,
      },
      {
        id: 'initiatives',
        label: 'Transformation Initiatives',
        type: 'textarea',
        placeholder: 'Major programs and initiatives...',
        required: true,
      },
    ],
  },
  {
    id: 'tpl-ops-update',
    name: 'Operations Update',
    description: 'Operational performance with production data and project status.',
    category: 'operations',
    slideCount: 14,
    lastUpdated: '2025-01-15',
    version: '1.8',
    fields: [
      {
        id: 'period',
        label: 'Reporting Period',
        type: 'text',
        placeholder: 'January 2025',
        required: true,
      },
      {
        id: 'production',
        label: 'Production Volume',
        type: 'text',
        placeholder: '95,000 boe/d',
        required: true,
      },
      {
        id: 'utilization',
        label: 'Refinery Utilization (%)',
        type: 'number',
        placeholder: '92',
        required: true,
      },
      {
        id: 'highlights',
        label: 'Operational Highlights',
        type: 'textarea',
        placeholder: 'Key achievements and updates...',
        required: true,
      },
      {
        id: 'projects',
        label: 'Project Updates',
        type: 'textarea',
        placeholder: 'Status of capital projects...',
        required: false,
      },
    ],
  },
];
